import { Project } from './types';

// 여기에 학생들의 프로젝트 정보를 추가하거나 수정하세요.
// 이 파일이 실제 웹페이지에 반영됩니다.

export const PROJECTS: Project[] = [
  {
    id: 1,
    title: '한붓그리기 퍼즐',
    description: '하나의 연속된 선으로 모든 점을 연결하는 퍼즐 게임입니다. 도전해보세요!',
    author: '김혜민',
    thumbnailUrl: '/thumb1.jpg',
    projectUrl: 'https://famous-kitten-1bfb11.netlify.app/',
  },
  {
    id: 2,
    title: '슈팅 게임',
    description: '적들을 물리치고 레벨을 올려서 무기를 업그레이드 할 수 있는 슈팅게임입니다.',
    author: '김예건',
    thumbnailUrl: '/thumb2.jpg',
    projectUrl: 'https://profound-creponne-5fe9ca.netlify.app',
  },
  {
    id: 3,
    title: '병맛 고양이 만들기',
    description: '귀여운 고양이를 입양하세요. 고양이가 원하는 것은 무엇일까요?',
    author: '이지윤',
    thumbnailUrl: '/thumb3.jpg',
    projectUrl: 'https://warm-taiyaki-48136b.netlify.app',
  },
  {
    id: 4,
    title: '메모리 게임',
    description: '당신의 기억력을 테스트해보세요.',
    author: '이채빈',
    thumbnailUrl: '/thumb4.jpg',
    projectUrl: 'https://mosanmemory.netlify.app',
  },
  {
    id: 5,
    title: 'Infinite Dungeon',
    description: '몬스터를 물리치고 다양한 스킬을 획득하라',
    author: '최준혁',
    thumbnailUrl:  '/thumb5.jpg',
    projectUrl: 'https://dungeonmosan.netlify.app',
  },
  {
    id: 6,
    title: 'Project 6',
    description: '개발중...',
    author: '개발자',
    thumbnailUrl: null,
    projectUrl: null,
  },
  {
    id: 7,
    title: 'Project 7',
    description: '개발중...',
    author: '개발자',
    thumbnailUrl: null,
    projectUrl: null,
  },
  {
    id: 8,
    title: 'Project 8',
    description: '개발중...',
    author: '개발자',
    thumbnailUrl: null,
    projectUrl: null,
  },
  {
    id: 9,
    title: 'Project 9',
    description: '개발중...',
    author: '개발자',
    thumbnailUrl: null,
    projectUrl: null,
  },
  {
    id: 10,
    title: 'Project 10',
    description: '개발중...',
    author: '개발자',
    thumbnailUrl: null,
    projectUrl: null,
  },
  {
    id: 11,
    title: 'Project 11',
    description: '개발중...',
    author: '개발자',
    thumbnailUrl: null,
    projectUrl: null,
  },
  {
    id: 12,
    title: 'Project 12',
    description: '개발중...',
    author: '개발자',
    thumbnailUrl: null,
    projectUrl: null,
  },
];
